### PR TITLE
Fixed Typographical Errors In The Controller Chart's Readme

### PR DESCRIPTION
**Pull request by TheDarkula**

### CODE REVIEW

**Comment by TheDarkula** [comment]
@dovholuknf I think I spotted a small error :)

**Review by qrkourier — CHANGES_REQUESTED** [review]
Thank you for the fix! Instead, will you make these changes in the `charts/ziti-controller/README.md.gotmpl` file? That template renders as `charts/ziti-controller/README.md`.

**Comment by TheDarkula** [comment]
@qrkourier Sure thing!
I just committed the change to the template. Would you like me to undo the change to the markdown file?

**Review by qrkourier — APPROVED** [review]

**Comment by TheDarkula** [comment]
@qrkourier Ah, brilliant.
One of the workflows are [failing](https://github.com/openziti/helm-charts/actions/runs/6051673334/job/16423673563?pr=132), however:
```
cat: /tmp/miniziti-client.log: No such file or directory
```

**Comment by qrkourier** [comment]
> One of the workflows are [failing](https://github.com/openziti/helm-charts/actions/runs/6051673334/job/16423673563?pr=132), however:

I see that, too. If you update your branch from main, you'll have a pinned version of the CI script before the bug was introduced. Then it should work.

**Comment by TheDarkula** [comment]
@qrkourier All done :)

**Pull request merged**
